frontend/config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from lee_fishing.fishing_equipment.views import RootRedirect

urlpatterns = [
    path("", RootRedirect.as_view(), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("lee_fishing.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("basket/", include("lee_fishing.fishing_net.urls", namespace="baskets")),
    path("shop/", include("lee_fishing.fishing_equipment.urls", namespace="products")),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

frontend/lee_fishing/fishing_equipment/urls.py
from django.urls import path

from lee_fishing.fishing_equipment.views import CategoryDetailView, CategoryListView, ProductDetailView

app_name = 'equipment'
urlpatterns = [
    path("", view=CategoryListView.as_view(), name="list"),
    path("<str:slug>/", view=CategoryDetailView.as_view(), name="detail"),
    path("<str:category>/<str:slug>/", view=ProductDetailView.as_view(), name="product"),
]

frontend/lee_fishing/fishing_net/urls.py
from django.urls import path

from lee_fishing.fishing_net.views import (
    BasketDetailView,
    BasketDeleteItemView,
    BasketAddItemView,
    CheckoutView,
    DummyView,
    CongratulationsView)

app_name = "basket"
urlpatterns = [
    path("", view=BasketDetailView.as_view(), name="basket"),
    path("add/<str:item>", view=BasketAddItemView.as_view(), name="add_item"),
    path("delete/<str:item>", view=BasketDeleteItemView.as_view(), name="delete_item"),
    path("checkout", view=CheckoutView.as_view(), name="checkout"),
    path("bye", view=CongratulationsView.as_view(), name="congrats"),
    path("ping", view=DummyView.as_view(), name="ping")
]

frontend/lee_fishing/users/urls.py
from django.urls import path

from lee_fishing.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

frontend/lee_fishing/fishing_equipment/models.py
import uuid

from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

from lee_fishing.fishing_equipment.managers import ProductManager


class Category(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=100, null=False, blank=False)
    slug = models.SlugField(null=False, blank=False, unique=True)

    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']
        verbose_name_plural = 'Categories'


class Product(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=100, null=False, blank=False)
    description = models.TextField(blank=True)
    slug = models.SlugField(null=False, blank=False, unique=True)

    primary_category = models.ForeignKey(Category,
                                         on_delete=models.DO_NOTHING, null=False, blank=False,
                                         related_name='primary_products'
                                         )
    categories = models.ManyToManyField(Category, blank=True)

    picture = models.ImageField(upload_to='products', null=True, blank=True)
    smaller_picture = ProcessedImageField(upload_to='product_thumbs',
                                          processors=[ResizeToFill(200, 200)],
                                          format='JPEG',
                                          options={'quality': 70},
                                          null=True, blank=True)

    in_stock = models.BooleanField()
    price = models.IntegerField()

    deleted_at = models.DateTimeField(null=True, blank=True)

    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    objects = ProductManager()

    @property
    def formatted_price(self):
        """
        Formatted price (as a string) for this product. There's so much
        wrong with this, you shouldn't use this for any serious
        ecommerce site!

        :return: formatted price... ish
        :rtype: str
        """

        return '$%.2f' % (self.price / 100)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']

frontend/lee_fishing/fishing_net/models.py
import uuid

from django.db import models
from django.contrib.auth import get_user_model

from lee_fishing.fishing_net.managers import BasketManager


class Basket(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING)

    deleted_at = models.DateTimeField(null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    order_id = models.TextField(null=True, blank=True, max_length=500)

    objects = BasketManager()

    def items_with_quantity(self):
        return self.basketitem_set.filter(quantity__gt=0)

    def add_item(self, item):
        if not self.modified_date:
            self.save()

        basket_item, created = self.basketitem_set.update_or_create(
            item_sku=item,
            defaults={
                'basket': self,
                'item_price': item.price,
            }
        )

        basket_item.quantity = 1 if created else basket_item.quantity+1
        basket_item.save()

    def remove_item(self, item):
        if not self.modified_date:
            return

        self.basketitem_set.filter(item_sku=item).update(quantity=0)


class BasketItem(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    basket = models.ForeignKey('Basket', on_delete=models.DO_NOTHING)
    item_sku = models.ForeignKey('fishing_equipment.Product', on_delete=models.DO_NOTHING)
    item_price = models.IntegerField()
    quantity = models.IntegerField(default=0)

    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('basket', 'item_sku',)

    @property
    def total_price_formatted(self):
        v = self.item_price * self.quantity
        return '$%.2f' % (v / 100)

frontend/lee_fishing/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

frontend/lee_fishing/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

frontend/lee_fishing/fishing_equipment/views.py
from django.db.models import Count
from django.http import HttpResponse
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView

from lee_fishing.fishing_equipment.models import Product, Category


class RootRedirect(RedirectView):
    permanent = False

    def get(self, request, *args, **kwargs):
        if self.request.META['HTTP_USER_AGENT'] == 'ELB-HealthChecker/2.0':
            return HttpResponse("Move along... nothing to see here.".encode('utf-8'), content_type="text/plain")

        return super(RootRedirect, self).get(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        return reverse('equipment:list')


class ProductDetailView(DetailView):
    queryset = Product.objects.not_deleted()

    def get_queryset(self):
        queryset = super(ProductDetailView, self).get_queryset()
        return queryset.filter(primary_category__slug=self.kwargs['category'])


class CategoryListView(ListView):
    model = Category
    paginate_by = 10

    def get_queryset(self):
        return self.model.objects.annotate(
            products=Count('primary_products')
        ).order_by('-products', 'title')


class CategoryDetailView(ListView):
    model = Category
    paginate_by = 10

    def get_queryset(self):
        return self.model.objects.get(slug=self.kwargs['slug']).primary_products.all()

frontend/lee_fishing/fishing_net/views.py
from timeit import default_timer

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import TemplateView, DetailView, RedirectView

from lee_fishing.fishing_equipment.models import Product
from lee_fishing.fishing_net.backend import BackendClient
from lee_fishing.fishing_net.models import Basket


class DummyView(TemplateView):
    template_name = 'fishing_net/ping.html'

    def get(self, request, *args, **kwargs):
        backend_client = BackendClient()
        kwargs['pong'] = backend_client.ping()

        return super().get(request, *args, **kwargs)


class BasketDetailView(LoginRequiredMixin, DetailView):
    model = Basket

    def get_object(self, queryset=None):
        return self.model.objects.current_for_user(self.request.user)


class BasketDeleteItemView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        basket = Basket.objects.current_for_user(self.request.user)
        basket.remove_item(Product.objects.get(slug=self.kwargs['item']))
        return reverse('baskets:basket')


class BasketAddItemView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        basket = Basket.objects.current_for_user(self.request.user)
        basket.add_item(Product.objects.not_deleted().get(slug=self.kwargs['item']))
        return reverse('baskets:basket')


class CheckoutView(LoginRequiredMixin, TemplateView):
    template_name = 'fishing_net/checkout.html'

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        start = default_timer()
        basket = Basket.objects.current_for_user(self.request.user)
        backend_client = BackendClient()

        r = backend_client.place_order()
        basket.order_id = r
        basket.save()

        end = default_timer()

        messages.add_message(request, messages.INFO, "It took " + str(end-start) + " seconds to process the order")

        return HttpResponseRedirect(reverse('basket:congrats'))


class CongratulationsView(LoginRequiredMixin, TemplateView):
    template_name = 'fishing_net/congrats.html'

frontend/lee_fishing/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

frontend/lee_fishing/templates/fishing_net/basket_detail.html
{% extends 'base.html' %}

{% block title %}Basket{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      &nbsp;
    </div>
    <div class="row justify-content-md-center">
      <div class="col">
        <div class="row">
          <table class="table table-striped">
            <thead>
            <tr>
              <th scope="col">Product</th>
              <th scope="col">Quantity</th>
              <th scope="col">Price</th>
              <th scope="col">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            {% for basket_item in basket.items_with_quantity %}
              <tr>
                <td>
                  {{ basket_item.item_sku.title }}
                </td>
                <td>
                  {{ basket_item.quantity }} <a href="{% url 'baskets:add_item' item=basket_item.item_sku.slug %}"><i
                  class="fas fa-plus"></i></a> / <i class="fas fa-minus"></i>
                </td>
                <td>
                  {{ basket_item.total_price_formatted }}
                </td>
                <td>
                  <a href="{% url 'baskets:delete_item' item=basket_item.item_sku.slug %}"><i
                    class="far fa-trash-alt"></i></a>
                </td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="row">
          <div class="col-md-12 text-right">
            <a href="{% url 'basket:checkout' %}" class="btn btn-primary">Checkout</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

frontend/lee_fishing/templates/fishing_net/checkout.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="row">
      &nbsp;
    </div>
    <div class="row justify-content-md-center">
      <div class="col">
        <div class="row">
          <div class="col">
            <h1>Checkout</h1>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <div class="alert alert-danger col-sm-6" role="alert">
              <i class="fas fa-user-ninja"></i> This is a terrible form, fix me!
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col">

            <form method="post">
              {% csrf_token %}
              <fieldset>
                <legend>Delivery Details</legend>

                <div class="form-group">
                  <label class="col-sm-3 control-label" for="full-name">Full Name</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" name="full-name" id="full-name"
                           placeholder="Full Name">
                  </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-sm-2 control-label" for="textinput">Line 1</label>
                  <div class="col-sm-9">
                    <input type="text" placeholder="Address Line 1" class="form-control">
                  </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-sm-2 control-label" for="textinput">Line 2</label>
                  <div class="col-sm-9">
                    <input type="text" placeholder="Address Line 2" class="form-control">
                  </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-sm-2 control-label" for="textinput">City</label>
                  <div class="col-sm-9">
                    <input type="text" placeholder="City" class="form-control">
                  </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-sm-2 control-label" for="textinput">State</label>
                  <div class="col-sm-4">
                    <input type="text" placeholder="State" class="form-control">
                  </div>

                  <label class="col-sm-2 control-label" for="textinput">Postcode</label>
                  <div class="col-sm-4">
                    <input type="text" placeholder="Post Code" class="form-control">
                  </div>
                </div>


                <!-- Text input-->
                <div class="form-group">
                  <label class="col-sm-2 control-label" for="textinput">Country</label>
                  <div class="col-sm-6">
                    <input type="text" placeholder="Country" class="form-control">
                  </div>
                </div>

              </fieldset>
              <fieldset>
                <legend>Payment</legend>
                <div class="form-group">
                  <label class="col-sm-3 control-label" for="card-holder-name">Name on Card</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" name="card-holder-name" id="card-holder-name"
                           placeholder="Card Holder's Name">
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label" for="card-number">Card Number</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" name="card-number" id="card-number"
                           placeholder="Debit/Credit Card Number">
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label" for="expiry">Card CVV</label>
                  <div class="col-sm-3">
                    <input type="text" class="form-control" name="expiry" id="expiry" placeholder="MM/YY">
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label" for="cvv">Card CVV</label>
                  <div class="col-sm-3">
                    <input type="text" class="form-control" name="cvv" id="cvv" placeholder="Security Code">
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-sm-offset-3 col-sm-9">
                    <button type="submit" class="btn btn-success"><i class="fas fa-shopping-cart" onClick="var e=this;setTimeout(function(){e.disabled=true;},0);return true;"></i> Pay Now</button>
                  </div>
                </div>
              </fieldset>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

frontend/lee_fishing/templates/fishing_net/congrats.html
{% extends 'base.html' %}

{% block content %}
  <h1>Stuff</h1>
{% endblock %}

frontend/lee_fishing/templates/fishing_net/ping.html
{% extends 'base.html' %}

{% block content %}
  <p>Artifishial Intelligence says: {{ pong }}</p>
{% endblock %}